/**
 * Seed the Phixo demo database with a realistic acute stroke ward:
 * six patients across the Day 1-7 window, with several days of simulated
 * session history generated by the same engine the live app uses.
 *
 * Run manually with `npm run seed` (deletes and regenerates everything),
 * or automatically on first launch via seedIfEmpty().
 */
import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import * as schema from "./schema";
import {
  simulateSession,
  seedForSession,
  ImpairmentProfile,
  EXERCISES,
} from "@/lib/simulator/engine";
import { mulberry32, hashSeed } from "@/lib/simulator/rng";

type Db = BetterSQLite3Database<typeof schema>;

interface SeedPatient {
  id: string;
  name: string;
  age: number;
  sex: string;
  bed: string;
  strokeType: string;
  affectedSide: string;
  /** 1-based acute day the patient is currently on */
  acuteDay: number;
  severity: "severe" | "moderate" | "mild";
  notes: string;
  profile: ImpairmentProfile;
  targetRepsPerDay: number;
  /** 0..1 — how much of the target this patient actually achieves */
  adherence: number;
}

const SEVERITY_PROFILES: Record<SeedPatient["severity"], ImpairmentProfile> = {
  severe: { baselineCapacity: 0.08, recoveryRate: 0.045, fatigueRate: 0.5, spasticityRisk: 0.004 },
  moderate: { baselineCapacity: 0.22, recoveryRate: 0.06, fatigueRate: 0.35, spasticityRisk: 0.002 },
  mild: { baselineCapacity: 0.38, recoveryRate: 0.07, fatigueRate: 0.25, spasticityRisk: 0.001 },
};

const PATIENTS: SeedPatient[] = [
  {
    id: "p-mizrahi",
    name: "Yosef Mizrahi",
    age: 68,
    sex: "M",
    bed: "A-102",
    strokeType: "Ischemic (MCA)",
    affectedSide: "right",
    acuteDay: 6,
    severity: "moderate",
    notes: "Right hemiparesis, good motivation. Family present most afternoons.",
    profile: SEVERITY_PROFILES.moderate,
    targetRepsPerDay: 350,
    adherence: 0.95,
  },
  {
    id: "p-cohen",
    name: "Miriam Cohen",
    age: 74,
    sex: "F",
    bed: "A-104",
    strokeType: "Ischemic (lacunar)",
    affectedSide: "left",
    acuteDay: 7,
    severity: "mild",
    notes: "Left-side weakness, strong recovery trend. Candidate for early discharge.",
    profile: SEVERITY_PROFILES.mild,
    targetRepsPerDay: 400,
    adherence: 1.0,
  },
  {
    id: "p-levi",
    name: "David Levi",
    age: 59,
    sex: "M",
    bed: "B-201",
    strokeType: "Hemorrhagic",
    affectedSide: "right",
    acuteDay: 4,
    severity: "severe",
    notes: "Dense right hemiplegia. Weak but consistent movement initiation from Day 2.",
    profile: SEVERITY_PROFILES.severe,
    targetRepsPerDay: 300,
    adherence: 0.7,
  },
  {
    id: "p-peretz",
    name: "Rivka Peretz",
    age: 81,
    sex: "F",
    bed: "B-203",
    strokeType: "Ischemic (MCA)",
    affectedSide: "left",
    acuteDay: 5,
    severity: "severe",
    notes: "Recurrent spasticity episodes — protocol capped at lower assist ceiling.",
    profile: { ...SEVERITY_PROFILES.severe, spasticityRisk: 0.008 },
    targetRepsPerDay: 300,
    adherence: 0.55,
  },
  {
    id: "p-barak",
    name: "Noa Barak",
    age: 52,
    sex: "F",
    bed: "C-301",
    strokeType: "Ischemic (PCA)",
    affectedSide: "right",
    acuteDay: 3,
    severity: "moderate",
    notes: "Young stroke, high motivation. Husband operates device evenings.",
    profile: SEVERITY_PROFILES.moderate,
    targetRepsPerDay: 400,
    adherence: 1.05,
  },
  {
    id: "p-demo",
    name: "Avi Goldman",
    age: 66,
    sex: "M",
    bed: "C-305",
    strokeType: "Ischemic (MCA)",
    affectedSide: "left",
    acuteDay: 1,
    severity: "moderate",
    notes: "Admitted this morning. First Phixo session pending — use for live demo.",
    profile: SEVERITY_PROFILES.moderate,
    targetRepsPerDay: 300,
    adherence: 0,
  },
];

const SESSION_HOURS = [9, 11.5, 14, 16.5, 19];

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function daysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
}

export function seedIfEmpty(db: Db): void {
  const existing = db.select({ id: schema.patients.id }).from(schema.patients).limit(1).all();
  if (existing.length > 0) return;
  seed(db);
}

export function seed(db: Db): void {
  db.delete(schema.samples).run();
  db.delete(schema.reps).run();
  db.delete(schema.safetyEvents).run();
  db.delete(schema.sessions).run();
  db.delete(schema.protocols).run();
  db.delete(schema.patients).run();

  const now = new Date();

  for (const p of PATIENTS) {
    const admission = daysAgo(p.acuteDay - 1);
    db.insert(schema.patients)
      .values({
        id: p.id,
        name: p.name,
        age: p.age,
        sex: p.sex,
        bed: p.bed,
        strokeType: p.strokeType,
        affectedSide: p.affectedSide,
        admissionDate: isoDate(admission),
        severity: p.severity,
        notes: p.notes,
        baselineCapacity: p.profile.baselineCapacity,
        recoveryRate: p.profile.recoveryRate,
        fatigueRate: p.profile.fatigueRate,
        spasticityRisk: p.profile.spasticityRisk,
      })
      .run();

    const exerciseIds =
      p.severity === "severe"
        ? ["elbow_flex", "wrist_ext", "knee_flex"]
        : ["elbow_flex", "shoulder_abd", "wrist_ext", "knee_flex"];

    db.insert(schema.protocols)
      .values({
        patientId: p.id,
        exercises: JSON.stringify(exerciseIds),
        targetRepsPerDay: p.targetRepsPerDay,
        maxAssistPct: p.id === "p-peretz" ? 80 : 95,
        sessionMinutes: 30,
        updatedAt: now.toISOString(),
      })
      .run();

    // History: full days 0 .. acuteDay-2, partial today (only morning sessions).
    for (let dayIndex = 0; dayIndex < p.acuteDay; dayIndex++) {
      const isToday = dayIndex === p.acuteDay - 1;
      const dayRng = mulberry32(hashSeed("day", p.id, dayIndex));
      const sessionsToday = isToday
        ? Math.min(2, SESSION_HOURS.length) // morning sessions only for "today"
        : 3 + Math.floor(dayRng() * 3);

      // Severe patients ramp up slowly over the first days.
      const rampFactor = Math.min(1, 0.4 + 0.2 * dayIndex);
      const dayTarget = Math.round(p.targetRepsPerDay * p.adherence * rampFactor);
      if (dayTarget === 0) continue;
      const perSession = Math.max(20, Math.round(dayTarget / sessionsToday));

      for (let s = 0; s < sessionsToday; s++) {
        const exerciseId = exerciseIds[(dayIndex + s) % exerciseIds.length];
        const sessionSeed = seedForSession(p.id, dayIndex, s);
        const targetReps = Math.max(
          10,
          Math.round(perSession * (0.85 + dayRng() * 0.3))
        );
        const sim = simulateSession({
          profile: p.profile,
          dayIndex,
          seed: sessionSeed,
          maxAssistPct: p.id === "p-peretz" ? 80 : 95,
          targetReps,
        });

        const start = new Date(admission);
        start.setDate(start.getDate() + dayIndex);
        start.setHours(Math.floor(SESSION_HOURS[s]), (SESSION_HOURS[s] % 1) * 60, 0, 0);
        const end = new Date(start.getTime() + sim.durationMs);
        const sessionId = `s-${p.id}-${dayIndex}-${s}`;

        db.insert(schema.sessions)
          .values({
            id: sessionId,
            patientId: p.id,
            exerciseId,
            startedAt: start.toISOString(),
            endedAt: end.toISOString(),
            repCount: sim.repCount,
            avgPatientRangePct: sim.avgPatientRangePct,
            avgAssistPct: sim.avgAssistPct,
            avgQuality: sim.avgQuality,
            avgRomPct: sim.avgRomPct,
            operator: s >= 3 ? "family" : "patient",
          })
          .run();

        // Insert reps in chunks to keep statements bounded.
        const repRows = sim.reps.map((r) => ({
          sessionId,
          tMs: r.tMs,
          initiationVelDegS: r.initiationVelDegS,
          patientRangePct: r.patientRangePct,
          assistPct: r.assistPct,
          quality: r.quality,
          romPct: r.romPct,
          durationMs: r.durationMs,
        }));
        for (let i = 0; i < repRows.length; i += 200) {
          db.insert(schema.reps).values(repRows.slice(i, i + 200)).run();
        }

        for (const ev of sim.safetyEvents) {
          db.insert(schema.safetyEvents)
            .values({
              sessionId,
              patientId: p.id,
              type: ev.type,
              atIso: new Date(start.getTime() + ev.atMs).toISOString(),
              // Past days' events reviewed; today's still open.
              acknowledged: isToday ? 0 : 1,
            })
            .run();
        }
      }
    }
  }
}

// CLI entry: `npm run seed`
if (process.argv[1]?.endsWith("seed.ts")) {
  (async () => {
    const { db } = await import("./index");
    seed(db);
    const count = db.select().from(schema.sessions).all().length;
    console.log(`Seeded ${PATIENTS.length} patients, ${count} sessions.`);
  })();
}

export { EXERCISES };
