import Link from "next/link";
import { notFound } from "next/navigation";
import { getPatientDetail } from "@/lib/data";
import { EXERCISES } from "@/lib/simulator/engine";
import { SessionPlayer } from "@/components/session-player";
import { PhixoLogo } from "@/components/phixo-logo";
import { Badge } from "@/components/ui/badge";

export const dynamic = "force-dynamic";

export default async function SessionPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const detail = getPatientDetail(id);
  if (!detail) notFound();
  const { patient, protocol, day, repsToday } = detail;
  const exerciseIds: string[] = JSON.parse(protocol.exercises);
  const exercises = EXERCISES.filter((e) => exerciseIds.includes(e.id)).map((e) => ({
    id: e.id,
    name: e.name,
  }));

  return (
    <main className="mx-auto flex w-full max-w-4xl flex-1 flex-col gap-6 px-6 py-8">
      <header className="flex items-center justify-between">
        <Link href={`/patient/${patient.id}`}>
          <PhixoLogo className="text-xl" />
        </Link>
        <div className="flex items-center gap-2">
          <span className="text-sm text-muted-foreground">{patient.name}</span>
          <Badge variant="secondary">Day {Math.min(day, 7)} of 7</Badge>
        </div>
      </header>

      <SessionPlayer
        patientId={patient.id}
        patientName={patient.name}
        affectedSide={patient.affectedSide}
        dayIndex={day - 1}
        profile={{
          baselineCapacity: patient.baselineCapacity,
          recoveryRate: patient.recoveryRate,
          fatigueRate: patient.fatigueRate,
          spasticityRisk: patient.spasticityRisk,
        }}
        maxAssistPct={protocol.maxAssistPct}
        targetRepsPerDay={protocol.targetRepsPerDay}
        repsTodayInitial={repsToday}
        exercises={exercises}
      />

      <p className="text-center text-xs text-muted-foreground">
        Simulated Phixo device — sensor signals are generated by the demo engine.
      </p>
    </main>
  );
}
