import Link from "next/link";
import { notFound } from "next/navigation";
import { getPatientDetail } from "@/lib/data";
import { SAFETY_EVENT_LABELS, SafetyEventType } from "@/lib/simulator/engine";
import { PhixoLogo } from "@/components/phixo-logo";
import { PrintButton } from "@/components/print-button";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

export const dynamic = "force-dynamic";

export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const detail = getPatientDetail(id);
  if (!detail) notFound();
  const { patient, protocol, day, daily, alerts, totalReps } = detail;
  const firstDay = daily[0];
  const lastDay = daily.at(-1);

  return (
    <main className="mx-auto flex w-full max-w-3xl flex-1 flex-col gap-6 px-6 py-8 print:py-2">
      <header className="no-print flex items-center justify-between">
        <Link href={`/dashboard/${patient.id}`}>
          <PhixoLogo className="text-xl" />
        </Link>
        <div className="flex gap-2">
          <Button variant="outline" asChild>
            <Link href={`/dashboard/${patient.id}`}>Back</Link>
          </Button>
          <PrintButton />
        </div>
      </header>

      <section className="border-b pb-4">
        <div className="flex items-center justify-between">
          <PhixoLogo className="hidden text-lg print:inline-flex" />
          <h1 className="text-xl font-semibold">Acute rehabilitation summary</h1>
          <span className="text-sm text-muted-foreground">
            {new Date().toLocaleDateString()}
          </span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">
          Generated by the Phixo companion platform for handover / EMR filing. Demo data —
          simulated device.
        </p>
      </section>

      <section className="grid grid-cols-2 gap-x-8 gap-y-1 text-sm">
        <p><span className="text-muted-foreground">Patient:</span> {patient.name}</p>
        <p><span className="text-muted-foreground">Age / sex:</span> {patient.age} / {patient.sex}</p>
        <p><span className="text-muted-foreground">Diagnosis:</span> {patient.strokeType}, {patient.affectedSide} hemiplegia ({patient.severity})</p>
        <p><span className="text-muted-foreground">Admitted:</span> {patient.admissionDate} (Day {Math.min(day, 7)})</p>
        <p><span className="text-muted-foreground">Bed:</span> {patient.bed}</p>
        <p><span className="text-muted-foreground">Daily target:</span> {protocol.targetRepsPerDay} repetitions</p>
      </section>

      <section>
        <h2 className="mb-2 font-medium">Therapy delivery</h2>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Acute day</TableHead>
              <TableHead className="text-right">Repetitions</TableHead>
              <TableHead className="text-right">% of target</TableHead>
              <TableHead className="text-right">Patient force</TableHead>
              <TableHead className="text-right">Device assist</TableHead>
              <TableHead className="text-right">Quality</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {daily.map((d) => (
              <TableRow key={d.date}>
                <TableCell>Day {d.day} · {d.date}</TableCell>
                <TableCell className="text-right tabular-nums">{d.reps}</TableCell>
                <TableCell className="text-right tabular-nums">
                  {Math.round((d.reps / protocol.targetRepsPerDay) * 100)}%
                </TableCell>
                <TableCell className="text-right tabular-nums">
                  {d.avgPatientForcePct != null ? `${Math.round(d.avgPatientForcePct)}%` : "—"}
                </TableCell>
                <TableCell className="text-right tabular-nums">
                  {d.avgAssistPct != null ? `${Math.round(d.avgAssistPct)}%` : "—"}
                </TableCell>
                <TableCell className="text-right tabular-nums">
                  {d.avgQuality != null ? Math.round(d.avgQuality) : "—"}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </section>

      <section className="grid gap-1 text-sm">
        <h2 className="font-medium">Clinical interpretation (auto-generated)</h2>
        <p className="text-muted-foreground">
          Total of {totalReps.toLocaleString()} device-assisted repetitions across{" "}
          {daily.length} active day{daily.length === 1 ? "" : "s"}.{" "}
          {firstDay && lastDay && firstDay !== lastDay && firstDay.avgAssistPct != null && lastDay.avgAssistPct != null
            ? `Device assistance decreased from ${Math.round(firstDay.avgAssistPct)}% to ${Math.round(
                lastDay.avgAssistPct
              )}% while patient-generated force rose from ${Math.round(
                firstDay.avgPatientForcePct ?? 0
              )}% to ${Math.round(
                lastDay.avgPatientForcePct ?? 0
              )}%, consistent with early motor recovery. `
            : ""}
          {alerts.length > 0
            ? `${alerts.length} safety guardrail event${alerts.length === 1 ? "" : "s"} recorded (all auto-paused by the device).`
            : "No safety guardrail events recorded."}
        </p>
      </section>

      {alerts.length > 0 ? (
        <section>
          <h2 className="mb-2 font-medium">Safety events</h2>
          <ul className="grid gap-1 text-sm text-muted-foreground">
            {alerts.map((a) => (
              <li key={a.id}>
                {new Date(a.atIso).toLocaleString()} —{" "}
                {SAFETY_EVENT_LABELS[a.type as SafetyEventType] ?? a.type}
                {a.acknowledged ? " (reviewed)" : " (open)"}
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <footer className="mt-auto border-t pt-3 text-xs text-muted-foreground">
        Phixo companion platform · proof of concept · not for clinical use
      </footer>
    </main>
  );
}
